name: apptick
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.2
  lottie: ^2.2.0
  http: ^1.2.2
  flutter_secure_storage: ^8.0.0
  google_fonts: ^5.0.0
  simple_circular_progress_bar: ^1.0.2
  dashed_circular_progress_bar: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
